FROM node:alpine as builder
RUN apk add npm
WORKDIR '/app'
COPY ./package.json ./
RUN npm install
COPY . .
ENV CI=true
RUN npm run build

FROM nginx
EXPOSE 3000
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/build /usr/share/nginx/html